/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.agenda.view;

import br.com.agenda.PrincipalAgenda;
import br.com.agenda.dominio.Contato;
import br.com.agenda.dominio.Telefone;
import br.com.agenda.negocio.ManterContatoNegocio;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felipe
 */
public class FormularioContato extends javax.swing.JPanel {

    private Integer IDALTERACAO = null;

    /**
     * Creates new form FormularioContato
     */
    public FormularioContato(Contato c) {
        initComponents();
        if (c != null) {
            campoNome.setText(c.getNome());
            campoCpf.setText(c.getCpf());
            campoEmail.setText(c.getEmail());
            IDALTERACAO = c.getId();
        }

        List<Telefone> telefones = ManterContatoNegocio.pesquisarTelefones("");
        adicionarListaTelefonesTabela(telefones);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tituloContato = new javax.swing.JLabel();
        textoNome = new javax.swing.JLabel();
        textoCpf = new javax.swing.JLabel();
        textoEmail = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoCpf = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        buttonGravarContato = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        campoTipo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JTextField();
        buttonAdicionarTelefone = new javax.swing.JButton();
        buttonDeletarTelefone = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        campoDdd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTelefone = new javax.swing.JTable();

        setLayout(new java.awt.GridBagLayout());

        tituloContato.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tituloContato.setText("CONTATO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        add(tituloContato, gridBagConstraints);

        textoNome.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        textoNome.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(textoNome, gridBagConstraints);

        textoCpf.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        textoCpf.setText("CPF:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(textoCpf, gridBagConstraints);

        textoEmail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        textoEmail.setText("E-mail:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(textoEmail, gridBagConstraints);

        campoNome.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 6, 4);
        add(campoNome, gridBagConstraints);

        campoCpf.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 6, 4);
        add(campoCpf, gridBagConstraints);

        campoEmail.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 6, 4);
        add(campoEmail, gridBagConstraints);

        buttonGravarContato.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonGravarContato.setText("Gravar");
        buttonGravarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGravarContatoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        add(buttonGravarContato, gridBagConstraints);
        add(jLabel7, new java.awt.GridBagConstraints());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Telefone"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("TIPO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(jLabel5, gridBagConstraints);

        campoTipo.setColumns(6);
        campoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTipoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(campoTipo, gridBagConstraints);

        jLabel6.setText("TEL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(jLabel6, gridBagConstraints);

        campoTelefone.setColumns(7);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(campoTelefone, gridBagConstraints);

        buttonAdicionarTelefone.setText("+");
        buttonAdicionarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarTelefoneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 1;
        jPanel2.add(buttonAdicionarTelefone, gridBagConstraints);

        buttonDeletarTelefone.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 1;
        jPanel2.add(buttonDeletarTelefone, gridBagConstraints);

        jLabel8.setText("DDD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(jLabel8, gridBagConstraints);

        campoDdd.setColumns(3);
        campoDdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(campoDdd, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jPanel2, gridBagConstraints);

        tabelaTelefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipo", "DDD", "Telefone"
            }
        ));
        tabelaTelefone.setMaximumSize(new java.awt.Dimension(10, 80));
        tabelaTelefone.setName(""); // NOI18N
        tabelaTelefone.setRowHeight(20);
        tabelaTelefone.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tabelaTelefone);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGravarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGravarContatoActionPerformed
        if (campoNome.getText().isEmpty() || campoCpf.getText().isEmpty()
                || campoEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        } else {
            Contato c = new Contato();
            c.setCpf(campoCpf.getText());
            c.setNome(campoNome.getText());
            c.setEmail(campoEmail.getText());
            c.setId(IDALTERACAO);
            ManterContatoNegocio.adicionar(c);
            JOptionPane.showMessageDialog(this, "Contato salvo!");
            PrincipalAgenda.listarContatos();
        }
    }//GEN-LAST:event_buttonGravarContatoActionPerformed

    private void campoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTipoActionPerformed

    private void campoDddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDddActionPerformed

    private void buttonAdicionarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarTelefoneActionPerformed
        List<Telefone> listaTelefones = new ArrayList<>();
        Telefone t = new Telefone();
        t.setTipo(campoTipo.getText());
        t.setDdd(campoDdd.getText());
        t.setNumero(campoTelefone.getText());
        ManterContatoNegocio.adicionarTelefoneNaLista(t);
        adicionarListaTelefonesTabela(listaTelefones);
//        PrincipalAgenda.abrirTelaAdicao(c);


    }//GEN-LAST:event_buttonAdicionarTelefoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarTelefone;
    private javax.swing.JButton buttonDeletarTelefone;
    private javax.swing.JButton buttonGravarContato;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoDdd;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JTextField campoTipo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabelaTelefone;
    private javax.swing.JLabel textoCpf;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoNome;
    private javax.swing.JLabel tituloContato;
    // End of variables declaration//GEN-END:variables
public void adicionarListaTelefonesTabela(List<Telefone> telefones) {
        String[] colunas = {"Tipo", "DDD", "Telefone"};
        String[][] dados = new String[telefones.size()][colunas.length];
        for (int i = 0; i < telefones.size(); i++) {
            Telefone t = telefones.get(i);
            dados[i][0] = t.getTipo();
            dados[i][1] = t.getDdd();
            dados[i][2] = t.getNumero();
        }
        DefaultTableModel modelo = new DefaultTableModel(dados, colunas);
        tabelaTelefone.setModel(modelo);
    }
}
